= abas REST API Demo Clients


Demonstration of how you can use the abas REST API.


== Prerequisites

A Java Development Kit version 8 is needed. All further java dependencies (libraries needed at compile time
and at runtime) are managed and downloaded automatically by https://gradle.org/[Gradle].

== Generate Eclipse Project

Eclipse is our IDE of choice but this project doesn't stick to it.

Simply use

  ./gradlew eclipse

to generate Eclipse project and classpath files. If you want to use another IDE, feel free to apply
another plugin in `build.gradle` in the projects' directory.


== Build

The task

  ./gradlew build

downloads all external dependencies and compiles all projects.


== The Example Projects

Currently, there are three small projects demonstrating how you can use aspects of the abas REST API.

=== GroovyRESTClient

Uses https://github.com/jgritman/httpbuilder/wiki/RESTClient[`groovyx.net.http.RESTClient`] to send HTTP
requests to the RESTful web services. The connection is established in
`de.abas.mw.client.Utils#createClient()`. Find and modify connection properties there.

There are two examples in this project:

==== ListProducts

Searches at most 1000 products (objects in `obj/data/2:1`) with search words between `M` and `N` and
prints fields `nummer`, `such`, `sucherw`, the object's `rowCount` and its location.

==== CreateOpportunity

Creates a new opportunity (object in `obj/data/3:30`) within the user's workspace using filters for head
and table fields. Then it sets some field values, inserts a row and prints the result. Next, the editor
is committed and the correspondig working set is closed. Finally the URL for the now "latest-version" is
printed.

The example makes use of https://en.wikipedia.org/wiki/HATEOAS[HATEOAS] to find the right resources for
all state transitions. Only the initial URL for creating the opportunity is hard-coded.

=== RestAssuredClient

Uses https://github.com/jayway/rest-assured[`com.jayway.restassured.RestAssured`] Java API to send HTTP
requests to the RESTful web services and parse the responses.

There is just a small `main()` method in `de.abas.mw.client.RestAssuredClient` that demonstrates how you
can query customers using the RestAssured client API.

=== ResteasyClient

Uses the https://docs.jboss.org/resteasy/docs/3.0-beta-2/userguide/html/RESTEasy_Client_Framework.html[RESTEasy Client Framework]
to create client-side Java proxies for a customer object and a list of customers. For parsing the responses
https://github.com/jayway/JsonPath[JsonPath] is used.

The main class is `de.abas.mw.client.RestEasyClient`. Here, the connection is established and the results
are printed. The entry URL and HTTP methods are defined in `de.abas.mw.client.Customers` using javax annotations.
Model classes in package `de.abas.mw.client.model` define which fields are queried and where their values
can be found within the response's JSON structure.
